### ISSUE TITLE
Query Wikidata

### ISSUE THREAD

**Issue by ymBila** [bounswe/bounswe2019group5#57] opened 2019-04-30 20:00 UTC
Create a function to query Wikidata and return item names and images given a class id.

**Comment by ymBila** [comment] 2019-04-30 20:31
Created pull request, @furkan-kadioglu is the reviewer.

**Comment by multiminparvo** [comment] 2019-05-03 23:34
Since the issue is reviewed, we can close it

**Closed by multiminparvo** 2019-05-03 23:34 UTC
Labels: Backend, Effort: High, New Feature, Priority: Medium, Status: Review Needed
